#!/usr/bin/env ruby

src = File.expand_path(File.dirname(__FILE__)) + '/src/'
$:.push(src); Dir.entries(src).each { |r| require r if r =~ /\.rb$/ };

puts 'Enter a maze string to solve:'
string = ''

until ((line = gets) == "\n")
  string += line
end

maze = Maze.new(string)
puts maze.tiles

if (maze.shortest_path?)
  puts "The best solution is:"
  p maze.shortest_path.map { |tile| [tile.x, tile.y] }
else
  puts "There is no solution"
end


## Example Maze:

#####################################
# #   #     #A        #     #       #
# # # # # # ####### # ### # ####### #
# # #   # #         #     # #       #
# ##### # ################# # #######
#     # #       #   #     # #   #   #
##### ##### ### ### # ### # # # # # #
#   #     #   # #   #  B# # # #   # #
# # ##### ##### # # ### # # ####### #
# #     # #   # # #   # # # #       #
# ### ### # # # # ##### # # # ##### #
#   #       #   #       #     #     #
#####################################
